language: node_js

node_js:
  - '6'

env:
  global:
    - CXX="g++-4.8"
  matrix:
    - CI_TASK=lint
    - CI_TASK=test

matrix:
  allow_failures:
    - env: CI_TASK=test

script:
  - npm run $CI_TASK

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

cache:
  directories:
  - node_modules
